CREATE TABLE IF NOT EXISTS owners (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    building VARCHAR(50) NOT NULL,
    unit VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS staff (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL,
    phone VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS assets (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    status ENUM('正常', '维修中', '停用') NOT NULL DEFAULT '正常'
);

CREATE TABLE IF NOT EXISTS complaints (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    status ENUM('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL DEFAULT 'NEW',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_complaints_owner_id (owner_id),
    CONSTRAINT fk_complaints_owner
        FOREIGN KEY (owner_id) REFERENCES owners(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS billing_records (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    billing_month DATE NOT NULL,
    tax_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    electricity_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    gas_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    heating_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    property_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    total_fee DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_billing_owner_month (owner_id, billing_month),
    INDEX idx_billing_owner_id (owner_id),
    CONSTRAINT fk_billing_owner
        FOREIGN KEY (owner_id) REFERENCES owners(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
